# Base for our build versions
version: "0.1.0.{build}"

# Specify or build image
image: Visual Studio 2017

# Do not build if we added just an image
skip_commits:
  files:
    - GGOHud/*

# Specify our assembly information
assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

# Add Python 3.6 on the Path and use the tag if the build was trigered with one
init:
  - cmd: set PATH=C:\\Python36-x64;%PATH%
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }

# Maybe in the future we are going to need submodules
# Update PIP and install Markdown to convert description.md
install:
  - cmd: git submodule update --init --recursive
  - cmd: python -m pip install -U pip markdown

# Restore our NuGet packages
before_build:
  - cmd: nuget restore GGOHud.sln

# Now, build the solution and convert the description from Markdown to HTML
build_script:
  - cmd: msbuild.exe GGOHud.sln /t:Build /p:Configuration=Release;Platform=x64
  - cmd: python -m markdown -f 5modsDescription.html description.md

# Create artifacts to test the automated builds
after_build:
  - cmd: 7z a GGOHudBuild.7z %APPVEYOR_BUILD_FOLDER%\bin\x64\Release\* GGOHud\*.png

# And attach them to the build
artifacts:
  - path: GGOHudBuild.7z
    name: GGOHud SHVDN Mod with Pictures
