version: "1.0.0.{build}"
image: Visual Studio 2017

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))" }

before_build:
  - ps: Get-ChildItem -Filter *.sln -Name | Foreach-Object { nuget restore $_  }

build_script:
  - ps: Get-ChildItem -Filter *.sln -Name | Foreach-Object { msbuild.exe $_ /t:Build /p:Configuration=Release`;Platform=x64 }

after_build:
  - ps: Get-ChildItem -Directory -Name -Exclude "packages" | Foreach-Object { 7z a "$($_).7z" "$($env:APPVEYOR_BUILD_FOLDER)\$($_)\bin\x64\Release\*" }
  - ps: Get-ChildItem -Filter *.7z -Name | Foreach-Object { Push-AppveyorArtifact $_ }

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
  artifact: /.*\.7z/
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
