# Base for our build versions
version: "0.1.0.{build}"

# Specify or build image
image: Visual Studio 2017

# Do not build if we added just an image
skip_commits:
  files:
    - GGOHud/*

# Specify our assembly information
assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

# Use the tag if the build was trigered with one
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

# Maybe in the future we are going to need submodules
install:
  - cmd: git submodule update --init --recursive

# Restore our NuGet packages
before_build:
  - cmd: nuget restore GGOHud.sln

# Now, build the solution
build_script:
  - cmd: msbuild.exe GGOHud.sln /t:Build /p:Configuration=Release;Platform=x64

# Create artifacts to test the automated builds
after_build:
  - cmd: 7z a GGOHud.7z %APPVEYOR_BUILD_FOLDER%\bin\x64\Release\* GGOHud\*.png

# And attach them to the build
artifacts:
  - path: GGOHud.7z
    name: Mod with Pictures

# Autodeploy on tags
deploy:
  release: v$(appveyor_build_version)
  description: "Released from AppVeyor"
  provider: GitHub
  auth_token:
    secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
  artifact: GGOHud.7z
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
