version: "1.0.0.{build}"
image: Visual Studio 2017

environment:
  FIVEM_CLIENT: "819-c026422393b41af81102dc3c95e5e4ebf3793477"
  FIVEM_SERVER: "790-3909d11205eb157fb35625f312f1b7779352d70a"

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))" }

install:
  - ps: Invoke-WebRequest "https://runtime.fivem.net/artifacts/fivem/build_client/master/$($env:FIVEM_CLIENT)/diff/fivereborn/citizen/clr2/lib/mono/4.5/CitizenFX.Core.dll.xz" -OutFile (Join-Path $env:TEMP "CitizenFX.Core.dll.xz")
  - ps: Invoke-WebRequest "https://runtime.fivem.net/artifacts/fivem/build_client/master/$($env:FIVEM_CLIENT)/diff/fivereborn/citizen/clr2/lib/mono/4.5/CitizenFX.Core.pdb.xz" -OutFile (Join-Path $env:TEMP "CitizenFX.Core.pdb.xz")
  - ps: Invoke-WebRequest "https://runtime.fivem.net/artifacts/fivem/build_client/master/$($env:FIVEM_CLIENT)/diff/fivereborn/citizen/clr2/lib/mono/4.5/CitizenFX.Core.xml.xz" -OutFile (Join-Path $env:TEMP "CitizenFX.Core.xml.xz")
  - ps: 7z e (Join-Path $env:TEMP "CitizenFX.Core.dll.xz") -oSDK\FiveM_Client\
  - ps: 7z e (Join-Path $env:TEMP "CitizenFX.Core.pdb.xz") -oSDK\FiveM_Client\
  - ps: 7z e (Join-Path $env:TEMP "CitizenFX.Core.xml.xz") -oSDK\FiveM_Client\

  - ps: Invoke-WebRequest "https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/$($env:FIVEM_SERVER)/server.zip" -OutFile (Join-Path $env:TEMP "fivemserver.zip")
  - ps: 7z e (Join-Path $env:TEMP "fivemserver.zip") -oSDK\FiveM_Server\ citizen\clr2\lib\mono\4.5\CitizenFX.Core.*

before_build:
  - ps: Get-ChildItem -Filter *.sln -Name | Foreach-Object { nuget restore $_  }

build_script:
  - ps: Get-ChildItem -Filter *.sln -Name | Foreach-Object { msbuild.exe $_ /t:Build /p:Configuration=Release`;Platform=x64 }

after_build:
  - ps: Get-ChildItem -Directory -Name -Exclude "packages" | Foreach-Object { 7z a "$($_).7z" "$($env:APPVEYOR_BUILD_FOLDER)\$($_)\bin\x64\Release\*" }
  - ps: Get-ChildItem -Filter *.7z -Name | Foreach-Object { Push-AppveyorArtifact $_ }

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
  artifact: /.*\.7z/
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
