version: "1.0.0.{build}"
image: Visual Studio 2017

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

before_build:
  - ps: Get-ChildItem -Filter *.sln -Name | Foreach-Object { nuget restore $_  }

build_script:
  - cmd: msbuild.exe GGO.sln /t:Build /p:Configuration=Release;Platform=x64

after_build:
  - cmd: 7z a GGOCommon.7z %APPVEYOR_BUILD_FOLDER%\GGO.Common\bin\x64\Release\*
  - cmd: 7z a GGOSingleplayer.7z %APPVEYOR_BUILD_FOLDER%\GGO.Singleplayer\bin\x64\Release\*

artifacts:
  - path: GGOCommon.7z
    name: Common base for the mod
  - path: GGOSingleplayer.7z
    name: Singleplayer SHVDN mod

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
  artifact: GGOSingleplayer.7z,GGOCommon.7z
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
